### ISSUE TITLE
Is there any Security issue with API Key?

### ISSUE THREAD

**Issue by filippolcr** [snipcart/snipcart-demo-v3#3]
Exploring this repo and [this](https://github.com/snipcart/snipcart-nuxt-pwa), you configure Snipcart in the default.vue as follow, clearly indicating Snipcart API key.

```
 <div
   id="snipcart"
   data-api-key="snipcartApiKey"
   hidden />
```

Recently I've read [an official Nuxt blog post link](https://nuxtjs.org/blog/moving-from-nuxtjs-dotenv-to-runtime-config) that made me think.

Couldn't there be security concerns hardcoding Snipcart API key? 

Thanks

**Comment by JeanSebTr** [comment]
Hi @filippolcr !

This is a **Public** API Key. It is meant to be shared in your website sources. It is a good approach from a maintainability point of view to use environment variables to store it, but it doesn't have any security implications. In fact, even if you store it in environment variables, it must end up publicly accessible on your website for the cart to work.

In contrast, Secret API Keys to access our Rest API, must never be exposed in the source of your website and used from the frond-end. Those are sensitive.
